### ISSUE TITLE
Return result

### ISSUE THREAD

**Issue by sdunnedeloitte** [awslabs/aws-lambda-powershell-runtime#1]
Hi, love this new runtime. Can you recommend the best way to handle return messages?

I was looking to use an error handling function that can be called from anywhere in the script to return a standard json response and then exit the script but tried a few ways and doing an Exit always returns the powershell exit response, e.g.;

Response
{
  "errorMessage": "RequestId: b6a48129-9818-420c-a837-c7b03a05a696 Error: Runtime exited with error: exit status 1",
  "errorType": "Runtime.ExitError"
}

I'm sure this is super simple but what would be your recommendation on the best way to handle this so that whenver the function execute it always spits out a clean json response?

Many thanks!

Example function below:

function Send-PAPIReturnMessage($status_code=500, $success=$false, $custom_message) {
  # Return a properly formatted API result 

  $hash = [ordered]@{
      "statusCode" = $status_code
      headers = [ordered]@{
          "Strict-Transport-Security"="testing";
          "Cache-control"= "no-cache, no store";
      }
              body = [ordered]@{
          "success"=$success; 
          "message"=$custom_message;
          }
  }
  
  $json = $hash | ConvertTo-Json -Depth 99
  $json
  Exit 1
  }

if (!$LambdaInput.period) {
        Write-Host "period variable is null"
        Send-CMPAPIReturnMessage -status_code 500 -success $true -custom_message "period is not specified "
    }

Write-Host "This is the rest of my script which should never be hit"

**Comment by austoonz** [comment]
Glad you're liking the new runtime!

In terms of your issue, when `exit 1` is used, that will tell PowerShell to exit the process using the exit code 1 which is why you're seeing that response/error.

Instead of using exit, I modified the code as below and I believe it works as you'd like.

Using the Lambda Function handler: `script.ps1::Handler`

Code in the file `script.ps1`

```powershell
function Send-PAPIReturnMessage($status_code = 500, $success = $false, $custom_message) {
    # Return a properly formatted API result
    $hash = [ordered]@{
        "statusCode" = $status_code
        headers      = [ordered]@{
            "Strict-Transport-Security" = "testing";
            "Cache-control"             = "no-cache, no store";
        }
        body         = [ordered]@{
            "success" = $success;
            "message" = $custom_message;
        }
    }

    $json = $hash | ConvertTo-Json -Depth 99
    return $json
}

function Handler($LambdaInput, $LambdaContext){
    if (!$LambdaInput.period) {
        Write-Host "period variable is null"
        return (Send-PAPIReturnMessage -status_code 500 -success $true -custom_message "period is not specified")
    }

    Write-Host "This is the rest of my script which should never be hit"
}
```

**Comment by sdunnedeloitte** [comment]
Ah perfect, thanks! So literally the exit is the last thing written by the script, so need to ensure the return is in the main handler. Got it! Thanks again, really nice job on the runtime!
