### ISSUE TITLE
Terraform deploy pattern

### ISSUE THREAD

**Issue by fv-ian** [awslabs/aws-lambda-powershell-runtime#10]
@julianwood Would you be interested or willing to accept a terraform deploy pattern?

**Comment by julianwood** [comment]
Absolutely! Love Terraform. We have another PR which I'm waiting to review for a better module builder so may be worth incorporating that. https://github.com/awslabs/aws-lambda-powershell-runtime/pull/7

**Comment by julianwood** [comment]
Closing this for now, feel free to add any Terraform support.
