### ISSUE TITLE
Cannot find path '\source\module' because it does not exist.

### ISSUE THREAD

**Issue by swordfish291** [awslabs/aws-lambda-powershell-runtime#11]
Hello,

The build-PwshRuntimeLayer.ps1 script seems to be broken. Get-Content at line 28 takes the $_ from pipleline and its throwing error. If we replace $_ with $_.FullName. It works. 

Get-ChildItem -Path $sourcePath/modules/Private -Filter *.ps1 | ForEach-Object {Get-Content $_ | Select-Object -Skip 2 | Out-File -FilePath $sourcePath/modules/pwsh-runtime.psm1 -Append}

Thanks
Abdul

**Comment by swordfish291** [comment]
Another issue that I observed is that the Out-File messes up the encoding of the pwsh-runtime.psm1. I am not sure if anyone has observed this but I tested this on two machines and it ended up making the file unreadable. Adding -Encoding UTF8 with Out-File solved the problem.

**Comment by julianwood** [comment]
For the `build-PwshRuntimeLayer.ps1` issue, are you running this from the same folder?
I've tested this on PowerShell for Windows as well as Linux and am not able to reproduce.
If you do ` Get-ChildItem -Path $sourcePath/modules/Private -Filter *.ps1 | %{Write-Host $_}`, do you not get a list of filenames?
![image](https://user-images.githubusercontent.com/16637894/216319788-ff45f59e-cf41-4723-9c1c-7f4aa8d15620.png)
![image](https://user-images.githubusercontent.com/16637894/216319871-72da9369-3011-4f19-bb4a-9f1961e5ce4e.png)

**Comment by swordfish291** [comment]
It seems its having issues while running this in Windows PowerShell. Running it in PowerShell Core executes without a problem.


Windows PowerShell:
![image](https://user-images.githubusercontent.com/25719157/216798937-04f5686a-fbbe-42e4-a79d-27419afd89a5.png)

PowerShell Core:
![image](https://user-images.githubusercontent.com/25719157/216798963-ef64a6f2-3fe6-406e-8811-7281a685dcd6.png)

`$_.FullName` executes without issues on both PowerShell environements.

**Comment by austoonz** [comment]
I have this issue as well when I build locally. Windows PowerShell seems to resolve `$_` to `$_.Name` instead of `$_.FullName`.

I've pushed an update to the build script to change it to `$_.FullName`

**Comment by swordfish291** [comment]
Validated. Worrking as expected in Windows PowerShell and PowerShell core.
