### ISSUE TITLE
Stack deploy fails for example `demo-runtime-layer-function` -- Lambda layers too large

### ISSUE THREAD

**Issue by mtboren** [awslabs/aws-lambda-powershell-runtime#2]
Firstly, great stuff here -- hurray for this excellent capability of a custom PowerShell runtime (vs. getting to compile for a .NET runtime)!

In going through the example for [`demo-runtime-layer-function`](https://github.com/awslabs/aws-lambda-powershell-runtime/tree/main/examples/demo-runtime-layer-function), and when using PowerShell (`build-layers.ps1`) for creating/building the layers, I hit an issue when trying to deploy the CloudFormation stack via `sam deploy`:  the Lambda layers end up too large to create/publish in AWS.

## Expected Behavior
Stack deploys to AWS account successfully

## Actual Behavior
Stack fails to deploy when having used the `build-AWSToolsLayer.ps1` script (called by `build-layers.ps1`) to build the AWS.Tools layer. The info about the resource that fails and its reason:

Result | Type | Logical Resource | Reason
| :------ | :------ | :------------------ | :--------
`CREATE_FAILED` | `AWS::Lambda::Function` | `DemoPowerShellFunction` | Resource handler returned message: "Layers consume more than the available size of 262144000 bytes" [continued..]

## Seeming Cause
`build-AWSToolsLayer.ps1` leaves the temporary download file `AWS.Tools.zip` in the folder used as the `DemoAWSToolsLayer` Lambda layer -- this extra 70MB file is then included in said Lambda layer by `sam deploy`, which puts the size of all layers used in the Lambda function greater than the apparent 250MB limit from AWS.

## Seeming Fix
At least one way to fix would be to update code `build-AWSToolsLayer.ps1` that builds `DemoAWSToolsLayer` to also clean up the temp zip archive  `AWS.Tools.zip` (the code already cleans up the rest of the temporary items)

## Deeper Details
`aws-lambda-powershell-runtime\examples\demo-runtime-layer-function\build-layers.ps1` calls `aws-lambda-powershell-runtime\powershell-modules\AWSToolsforPowerShell\Demo-AWS.Tools\build-AWSToolsLayer.ps1`, which:
- downloads `AWS.Tools.zip` to `aws-lambda-powershell-runtime\powershell-modules\AWSToolsforPowerShell\Demo-AWS.Tools\`
- expands the zip archive to `aws-lambda-powershell-runtime\powershell-modules\AWSToolsforPowerShell\Demo-AWS.Tools\stage`
- copies select modules to `aws-lambda-powershell-runtime\powershell-modules\AWSToolsforPowerShell\Demo-AWS.Tools\modules` as expected/needed/desired
- removes staging dir `aws-lambda-powershell-runtime\powershell-modules\AWSToolsforPowerShell\Demo-AWS.Tools\stage`
- but _leaves_ the `aws-lambda-powershell-runtime\powershell-modules\AWSToolsforPowerShell\Demo-AWS.Tools\AWS.Tools.zip` intact
- so, at LambdaLayer creation time via `aws-lambda-powershell-runtime\examples\demo-runtime-layer-function\template.yml`, the temporary `AWS.Tools.zip` is included in the `DemoAWSToolsLayer` layer, and subsequent layer creation seemingly fails due to `Layers consume more than the available size` issue reported

**Comment by mtboren** [comment]
We can write the "clean up the temp downloaded .zip file" portion in lots of ways, of course. I have a reasonable working update to `build-AWSToolsLayer.ps1` that should also help prevent any such issues in the future by placing _all_ staging types of files into the `stage` folder, so the eventual removal of that temporary `stage` files kills all temporary things as desired, with no further tracking of, "oh, gotta be sure to clean up these other things, too" kinds of task.

Happy to submit a PR for consideration on this -- shall I? Let me know! 👍

**Comment by julianwood** [comment]
Thanks for spotting this. I've amended the download scripts, as suggested, to rather download `AWS.Tools.zip` to the stage area and then ensuring the cleanup runs on anything in `\stage`.

If you spot any other optimizations, happy to have your contribute.

**Comment by mtboren** [comment]
Superduper -- thanks, @julianwood for handling it! I'll be sure to try to contribute if I see some opportunities.
