### ISSUE TITLE
Installing modules example

### ISSUE THREAD

**Issue by alexandroivaldez** [awslabs/aws-lambda-powershell-runtime#29]
Would it be possible to add a walkthrough or example of how to add PowerShell modules, for example "Exchange Online PowerShell V3" module?

**Comment by mahu404** [comment]
hi @alexandroivaldez , I just work on this one for my project, you can check and use **powershell-modules/AWSToolsforPowerShell/AWS.Tools.S3EventBridge/build-AWSToolsLayer.ps1** as example, replace the url in this file to the url to download your module you want, 

And in your lambda function, you have to point directly to the file psm1, in this case this is "/opt/modules/netCore/ExchangeOnlineManagement.psm1".
