### ISSUE TITLE
Missing ICU package

### ISSUE THREAD

**Issue by juancrl** [awslabs/aws-lambda-powershell-runtime#33]
I've rebuilt the powershell-runtime to allow Amazon Linux 2023...
But now I'm getting 
"Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information." 
when starting my Lambda function. I can imagine this package is missing ?

**Comment by austoonz** [comment]
In your Lambda Function, try setting the environment variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to `1`.

**Comment by juancrl** [comment]
Thanks Andrew !!! Working 105% perfectly !!
(And now I realize the env var is documented in the given link :-(  ... Well, the power of reading :-) )

**Comment by julianwood** [comment]
Glad its working.
