### ISSUE TITLE
Lambda runtime invocations delayed by ~100 seconds when using PowerShell Custom Runtime

### ISSUE THREAD

**Issue by sean-r-williams** [awslabs/aws-lambda-powershell-runtime#34]
_\[AWS Support case ID: 172490056800549\]_

We're using the PowerShell Custom Runtime in conjunction with API Gateway to implement a webhook processor in PowerShell.

After moving our service to production, we began noticing some invocations are starting with most of their allotted execution time consumed. APIGW only allots 2 minutes, and our functions are starting with ~20 seconds remaining. This appears to be commensurate with load upon the function.

After enabling `POWERSHELL_RUNTIME_VERBOSE` on the Lambdas, we see logs that look like the following:
![image](https://github.com/user-attachments/assets/54d34888-7121-438d-9d2f-a03ca127dcf2)

At 12:49:39.985-.986, the runtime finishes sending the prior request (RequestID `2da4...927f`) response to the Runtime API. I see log lines indicating we hit `/NEXT` twice:
* Once at 12:49:39.986
* Once at 12:51:19.987

Lambda logged a START record for a request against this function instance (reqID `e565...7969`) at 12:49:43, about 3 seconds after we submitted the prior request's response. However, the runtime doesn't read the response stream until the second `/NEXT` request at 12:51:19.987.

Our function's P90 execution takes about 20 seconds currently (we make lots of non-parallelizable REST calls) so losing >80% of our execution time is far from ideal and is causing us to time out in some cases.

**Comment by sean-r-williams** [comment]
One of the possible explanations for the 100-second delay: .NET's `System.Net.HttpWebRequest` (the derivate of `.WebRequest` selected by the runtime for HTTP schemes) defaults to a timeout of [100 seconds](https://learn.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.timeout?view=net-8.0).

According to the [Lambda Runtime API docs](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html#runtimes-api-next), there's some differences between the reality of implementation and documented guidance:
* The docs mention not setting a timeout - in this case we have an implicit timeout of 100 seconds.
* The docs mention that the runtime may be frozen for several seconds - the START record was logged 3 seconds after the first `GET .../NEXT` occurred. It's not clear why this request hung for an additional 117 seconds without returning a response.

**Comment by julianwood** [comment]
Thanks for reporting. 

API Gateway response is max 29 seconds, so I wonder if there could be other factors at play here. 

Are you seeing longer end to end latency for some responses through APIGW-Lambda, or this is what it looks like from the logs?

Sometimes Lambda initiates request 1 but while unfreezing the execution environment A, another execution environment B finishes its unfreezing process before A, so Lambda sends invoke 1 to B, rather than A. 

This can look like hanging invokes that don't do anything. Although the logs seem to indicate a delay, the actual request is being handled elsewhere.

Are you able to use X-Ray to view traces through API Gateway + Lambda, or any monitoring on your client side to see if the clients are actually experiencing latency.

This is just a possibility. 

If there is an optimization possible via the .NET web request, certainly worth looking into improving that.

@austoonz, do you have any insights for this issue?

**Comment by sean-r-williams** [comment]
@julianwood 
> API Gateway response is max 29 seconds, so I wonder if there could be other factors at play here.

You're totally right - my apologies. The 120 second timeout seems to be what we have configured on the function - we can temporarily bump this while we troubleshoot. However, I doubt that would effect any change within API Gateway.

> Are you seeing longer end to end latency for some responses through APIGW-Lambda, or this is what it looks like from the logs?
We're seeing this present itself in a few areas:
* Lambda's intrinsic metrics for invocations (namely success/timeout and billed duration for the run)
* When our handlers start, `$LambdaContext.RemainingTime` is occasionally much less than we'd expect (normally just shy of 120 seconds, affected requests show ~20-25 seconds remaining at the start of the handler)
* Within the logs, mismatched sequencing between `START` records, lifecycle (starts and successes/timeouts) of `HttpWebRequests`)
 

> Are you able to use X-Ray to view traces through API Gateway + Lambda, or any monitoring on your client side to see if the clients are actually experiencing latency.

I'm having trouble getting X-Ray to work across APIGW+Lambda, but I do see an elevated quantity of 503s from API Gateway. Again, these are commensurate with load on our function. It's not clear if these are due to us going over the 30-second timeout from APIGW within our own code, or from the aforementioned delays in the event loop. The incidence of 503s appears higher than that of the event-loop delay, so it's possible APIGW is 503ing under both cases.

Our upstream client is an automated service that sends us webhooks in response to service-internal events, so we don't have a great telemetry story there.

@austoonz
> I can look to have a new branch up and running with System.Net.Http.HttpClient instead of System.Net.HttpWebRequest if that's something you're willing to trial
Yes, we would be happy to trial this. It's important to note that HttpClient also has a [default timeout value of 100 seconds](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-8.0#remarks) - moving to HttpClient might change underlying socket handling in a manner that's more conducive to Lambda freezing/unfreezing the environment, but I reckon the timeout value will still need to be changed nonetheless.

**Comment by austoonz** [comment]
I've created a dev branch that migrates the runtime API requests to `System.Net.Http.HttpClient`. You can find it here: https://github.com/austoonz/aws-lambda-powershell-runtime/tree/HttpClient

In my brief testing of the change it "works as expected" for my simple hello world testing.

When you can, feel free to build a runtime layer from that branch and see how you go.

**Comment by sean-r-williams** [comment]
Thanks @austoonz! I'm discussing deployment options with my team. I'll be OOF for some/all of next week, so it's possible we won't be able to deploy this until the week of 9/9.

**Comment by sean-r-williams** [comment]
@austoonz Initial smoke testing suggests the new branch alleviates this issue - unclear if it was specifically migrating to `HttpClient` or setting `InfiniteTimeout` on requests, but results are positive thus far.

Our load pattern changed last week due to some turn-down of upstream services, however, so we want to do a little more load testing with some real-world traffic. We've enabled this to test the performance of the runtime at the scale we were running at previously - I'll try to update this issue early next week.

**Comment by austoonz** [comment]
Thanks for the update @sean-r-williams. Good to hear it's initially looking good!

If all continues to look good we'll pull the code change into this repository. I'd prefer the code be on the `httpClient` anyway given `webClient` is marked deprecated.

**Comment by sean-r-williams** [comment]
@austoonz So far, everything looks good - load testing hasn't revealed a recurrence of this issue. Thanks for your patience - let us know if there's anything needed to get the change pulled in.

**Comment by austoonz** [comment]
That's great news @sean-r-williams. I'll get a PR opened (likely tomorrow) and will ping @julianwood for review.

**Comment by julianwood** [comment]
Thanks, fix is merged and latency should be improved. Please let us know if you find any issues with this.
